baseURL = 'https://jeffreyharmon.dev'
languageCode = 'en-us'
title = "jeffreyharmon.dev"

disableKinds = ["taxonomy", "term"]

[params]
favicon = "favicon.svg"
description = "Software Engineer | M.S. ICS | Eagle Scout"
dateFormat = "2006-01-02"
generateSocialCard = true

[params.socials]
github = "https://gh.pear.cx"
linkedin = "https://li.pear.cx"
itch = "https://itch.pear.cx"
email = "mailto:contact@jeffreyharmon.dev"

[params.author]
name = "Jeffrey Harmon"
email = "contact@jeffreyharmon.dev"

[markup.highlight]
lineNos = false
lineNumbersInTable = false
noClasses = false

[permalinks]
redirect = "/:slug/"
